### ISSUE TITLE
first step

### ISSUE THREAD

**Issue by EricDuy** [ShichaoSun/metaphor#2]
When I downloaded the word2vec pre-trained Google News corpus, it always failed to download halfway, prompting for a network error. It still doesn't work after changing the network. Have you ever seen this situation? Or do you have a new link to the corpus to share?
Thank you!

**Comment by ShichaoSun** [comment]
I downloaded the pre-trained word vectors from the official website  https://code.google.com/archive/p/word2vec/ but I haven't seen this situation.
Maybe you can try the link https://github.com/mmihaltz/word2vec-GoogleNews-vectors via `git clone` instead of accessing the Google Drive.

**Comment by EricDuy** [comment]
ok,thank you!
